/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  AppChat as AppChat
} from './components/app-chat/app-chat';

declare global {
  interface HTMLAppChatElement extends AppChat, HTMLElement {
  }
  var HTMLAppChatElement: {
    prototype: HTMLAppChatElement;
    new (): HTMLAppChatElement;
  };
  interface HTMLElementTagNameMap {
    "app-chat": HTMLAppChatElement;
  }
  interface ElementTagNameMap {
    "app-chat": HTMLAppChatElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-chat": JSXElements.AppChatAttributes;
    }
  }
  namespace JSXElements {
    export interface AppChatAttributes extends HTMLAttributes {
      
    }
  }
}

